### ISSUE TITLE
MERN integration

### ISSUE THREAD

**Issue by nmaro** [js-accounts/accounts#15]
Hey guys this is awesome. What's the state of this project? Can't yet install via npm install @accounts... Would be interested in implementing a [MERN](http://mern.io/) integration (see my motivation [here](https://medium.com/the-ideal-system/note-to-self-never-get-stuck-with-a-framework-again-7699bbd887b5#.hpjrpyrg5)) so if you are serious about maintaining this let me know!

**Comment by TimMikeladze** [comment]
Hi @nmaro, that's a good idea about the MERN integration. It's definitely something we can do. Would you like to take on this task once this project becomes a bit more mature?

Yes I'm serious about maintenance. 

The state of the project is that I'm working on the core accounts code, rest adapter, and react components at the moment. Currently I'm only focused on the client side due to work requirements (our backend isn't JS) but will eventually implement the rest backend in JS, the GraphQL support, followed by specific data store implementations. 

I'm expecting to publish the core client side functionality with the rest adapter and the material ui react components to NPM sometime this week.

**Comment by nmaro** [comment]
Sounds good! Yes I'd be interested in implementing a MERN integration. Could you write me a GO here, when it's ready?

BTW. hope you are keeping the UI separate from the client-side core - I'd probably use it with my own UI I'm already using with meteor accounts. Cheers!
