### ISSUE TITLE
Getting started with development

### ISSUE THREAD

**Issue by gadicc** [js-accounts/accounts#16]
@TimMikeladze, I really want to help but I'm not sure yet where to jump in...  Could I ask for:

1) A general update.  What's done and what you're busy working on now, where you'd like help / what's important but you're not currently working on.

2) It sounds from the other issue that maybe you're already using this with one of your sites... how does one get started?  Could you post some basic setup notes?

I noticed also that you're using REST for a lot of stuff (vs GraphQL).  I actually think this is the way to go, for now at least.  Firstly, since we need control over incoming requests anyway for the popup auth flow, but also, since it's incredibly unpleasant to setup Apollo atm with multiple sources for schemas.  Even though I had a working (but ugly) workaround in my meteor and saturn starters, this was the thing I was most worried about and the most complicated to set up.  I'd say for this particular project REST is a better fit at this stage.

**Comment by TimMikeladze** [comment]
Hi @gadicc 

1. I'm currently working on the client side, have written 0 server code. Amongst other things I've implemented the login and signout code. There's still edge cases to handle, token handling code, plus running all the user configured hooks. You could jump into writing the server side code. I haven't written any backend yet at all. There's also always low hanging fruit and other issues. I'm assigned to the stuff I'm working on, everything else is up for grabs. 

2. I'll update the readmes. 

I am focused on REST at the moment but that's because it's a requirement for me in a project. I agree about handling schemas, but it's not a major issue. The transport it turns out plays a surprisingly small role in all this when compared to the rest of the code.

**Comment by gadicc** [comment]
Hey Tim, thanks for the update.  Sorry for my late reply.  I'm currently travelling for the next two weeks with limited PC access.  Had planned to do some work on this before I left but my final days got unexpectedly hectic.  Promise to up my commits during December :)  Will be very happy to do the server implementation then if I'm not holding things up.

**Comment by TimMikeladze** [comment]
@gadicc I'm closing this issue. I'm starting the database work for this later in the week.
